# Load the required Python and pandas modules
module load python pandas

# Define the target rules

# Rule for running Sourmash sketch
rule run_sourmash_sketch:
    input:
        "input/{sample}_1.fastq.gz",
        "input/{sample}_2.fastq.gz"
    output:
        "sketches/{sample}.sig"
    shell:
        "sourmash sketch dna -p scaled=1000,k=31,51,k=101,abund {input[0]} {input[1]} --name '{wildcards.sample}' -o {output}"

# Rule for running Sourmash prefetch
rule run_sourmash_prefetch:
    input:
        "sketches/{sample}.sig"
    output:
        "{sample}_k51_prefetch.csv"
    shell:
        "sourmash prefetch {input} db.trnL-entrez-ref.fasta.sig --dna --ksize 51 --threshold-bp 0 -o {output}"

# Rule for performing inner join with common_names.csv
rule perform_inner_join:
    input:
        "{sample}_k51_prefetch.csv",
        "common_names.csv"
    output:
        "{sample}_prefetch_cmon.csv"
    script:
        "join_csv.py"

# Define the workflow to run the rules for all samples
rule all:
    input:
        expand("{sample}_prefetch_cmon.csv", sample=SAMPLES)
