# Snakemake Config File

group: "weight_loss"

dbs:
#    crop_chloroplast.1000: "../db/Sketched-db/db.crop-plant-entrez.ref.1000.sig.zip"
#    all_chloroplast.1000: "../db/Sketched-db/db.plant-entrez-ref.1000.sig.zip"    
    crop_chloroplast: "../db/Sketched-db/db.crop-plant-entrez.ref.100.sig.zip"
    all_chloroplast: "../db/Sketched-db/db.plant-entrez-ref.100.sig.zip"
    trnl: "../db/Sketched-db/db.trnL-entrez-ref.fasta.bz2.sig"
    #gtdb: "../db/Sketched-db/gtdb-rs214-reps-all-k.zip"

k_size:
  - 21
  - 31
  - 51

scale:
  - 100
  - 1000